### ISSUE TITLE
How does this compare to eslint-plugin-import-order-alphabetical?

### ISSUE THREAD

**Issue by randycoulman** [Tibfib/eslint-plugin-import-helpers#2]
Thanks for creating this plugin!  This addresses one of my most-wanted enhancements to eslint-plugin-import.

Recently, I started using [eslint-plugin-import-order-alphabetical](https://github.com/janpaul123/eslint-plugin-import-order-alphabetical) to address the issue.

I see that you provide a couple of options for what the sorting order should be within the groups, but other than those enhancements, I'm wondering how similar these two plugins are.  

If they're close, is there a way to perhaps combine efforts to make one really great plugin (or perhaps have something awesome to push back upstream to eslint-plugin-import)?

**Comment by willhoney7** [comment]
Hi!

So, that eslint-plugin-import-order-alphabetical looks like really similar to this fork of [eslint-plugin-import](https://github.com/dannysindra/eslint-plugin-import/blob/alphabetize/src/rules/order.js). I'm honestly not sure which came first. I based this rule off of the fork I linked.

This rule offers two enhancements:
- in both of these other versions, the sorting alphabetically doesn't work with the `newlines-between` option. It thinks there should be a new line between every import statement.
- regexp matching for groups. this is a big enhancement and was the focus of this project.

I created this new project because I needed something that worked and that I could control so we could get this in place ASAP at my job. I decided to open source it because I'm sure others have wanted this too. I'm happy to contribute to whatever is best in the end, but for now, I need a solution. (I'm also happy to accept contributions).

**Comment by randycoulman** [comment]
Ah, cool!  I hadn't noticed the regexp matching for groups.  I had skimmed the docs and they looked similar to eslint-plugin-import and eslint-plugin-import-order-alphabetical so I assumed it was the same in that regard.  That might be worth highlighting in the README, because it's a nice value-add.

eslint-plugin-import-order-alphabetical does work with the `newlines-between` option, but sometimes requires me to save the file multiple times to auto-fix things all the way.  I'm now anxious to try out this plugin to see if it's better in that regard.

Thanks again for sharing your work and for the quick response!

**Comment by willhoney7** [comment]
Thanks for the suggestion! I added a code snippet to better explain what the rule can do in the initial readme. 

I'm still working to differentiate the documentation and improve it from the original fork. 

Also, that's good to know that `eslint-plugin-import-order-alphabetical` does work with `newlines-between`! I just casually looked at the source and it seemed to have the same issue that I resolved but I didn't actually try it.
