### ISSUE TITLE
Relative import mistaken as modules

### ISSUE THREAD

**Issue by hyoretsu** [Tibfib/eslint-plugin-import-helpers#31]
If you use relative modules with baseUrl config in tsconfig.json, they're now treated as modules, just like `import React from 'react'`. (It's either that or `import asd from ../../../../components`) Don't know if there's a way to fix that but I'll just add '/^components/'

**Comment by willhoney7** [comment]
Hi!

This is working as designed (for now). The plugin doesn't do any reading/analyzing of the tsconfig.json. 

You're correct, if you want to treat them differently, add a regexp group. Since it's just a one-time configuration thing, I don't think it's worth introducing more complexity when the regexp suffices. Open for discussion...
