### ISSUE TITLE
does it support "^7.12.1" ?

### ISSUE THREAD

**Issue by RicardoBrito1938** [Tibfib/eslint-plugin-import-helpers#34]
Hello guys, i followed the documentation but it did work on my react native project, is this lib supported on "^7.12.1"?

**Comment by RicardoBrito1938** [comment]
any ideia?

**Comment by willhoney7** [comment]
Hi there! There's too much going on here for me to be able to help. ESLint should work just fine with react-native, since it's still just javascript/typescript files. I would look for a guide that shows how to use ESLint with react-native, and then follow the readme to add this plugin. Sorry, I can't help more.
