### ISSUE TITLE
Support for eslint v9

### ISSUE THREAD

**Issue by robbieaverill** [Tibfib/eslint-plugin-import-helpers#56]
Hey team,

eslint v9 is the latest release. Could we update this plugin to support it?

Notes: https://eslint.org/docs/latest/use/migrate-to-9.0.0#breaking-changes-for-plugin-developers

Thanks

**Comment by Aluisio** [comment]
It's sad that a project with over 100k weekly downloads seems abandoned 😔

**Comment by shredor** [comment]
I have peer dependency warning, but it works with eslint v9
```

import importPlugin from 'eslint-plugin-import-helpers';

...
plugins: {
  'import-helpers': importPlugin,
},
...
```

**Comment by willhoney7** [comment]
Hey all, I cut the v2 release which has support for v9. Let me know if you run into any new issues.

As an aside, I've stopped active development of this because I think this package does a much better job at solving the same problem and is what I now use: [@ianvs/prettier-plugin-sort-imports](https://github.com/IanVS/prettier-plugin-sort-imports)
